apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: staging
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mariadb
